name = "theme-extension"

uid = "65b30aae-2fc0-9b48-3e28-e6bf3e801b92f9c75ad7"

type = "theme"

[extension]
type = "app"
name = "Draft Order Embed"
targets = ["app_embeds"]

[[extension.app_embeds]]
name = "Draft Order App Embed"
enablement = { type = "app_embeds" }
enabled_on = { templates = ["cart"], snippets = ["cart-notification-button"] }